CREATE TABLE IF NOT EXISTS dispositivos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    icono VARCHAR(50) NOT NULL DEFAULT 'tv',
    estado ENUM('en_linea', 'en_espera') NOT NULL DEFAULT 'en_espera',
    online BOOLEAN NOT NULL DEFAULT TRUE,
    watts INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
